feat: Add Transaction class with verification logic
news-ladder/php-publisher-api pull request #9
Opened 2024-11-26 20:28 UTC by damasch

- Introduced the `Transaction` class to handle transaction data.
- Implemented properties for domain, URL, name, external article ID, magazine key, and checkout token.
- Added a constructor to initialize transaction properties.
- Included a magic getter method for dynamic property access.
- Developed a `verify` method to validate transactions against the backend API.
- Integrated `Config` and `NewsLadderRequest` for API interaction.

This implementation establishes the foundation for managing and verifying transactions in the NewsLadder Publisher API.

closes #8

2024-11-26 20:29 UTC, damasch commented
Unit test are comming

2024-11-26 21:50 UTC, pascaliske requested changes

2024-11-26 21:50 UTC, pascaliske commented on src/Transaction.php
> +
Within the sub-namespace the use statement can be skipped and the class can be used directly, e.g. `Config` in this case.

```suggestion
```

2024-11-26 21:50 UTC, pascaliske commented on src/Transaction.php
> +        $url = $config.get("origins", "api_url") . '/transaction/verify';
JS is calling. This should be converted to PHP syntax. Also using `sprintf` makes the code more readable in my opinion.

```suggestion
        $url = sprintf("%s/transaction/verify", $config->get("origins", "api_url"));
```

2024-11-29 07:40 UTC, pascaliske approved these changes

2024-11-29 07:41 UTC, merged